%% Copyright (c) 2017 Erik Reitsma <development@ernovation.com>
-module(acpi_tables).

-export([parse_table/2]).

parse_table(fadt, Data) ->
    fields_parser:parse_fields(
      [{firmware_ctl, dword},
       {dsdt, dword},
       {unused, byte},
       {preferred_pm_profile, byte},
       {sci_int, word},
       {smi_cmd, dword},
       {acpi_enable, byte},
       {acpi_disable, byte},
       {s4bios_req, byte},
       {pstate_cnt, byte},
       {pm1a_evt_blk, dword},
       {pm1b_evt_blk, dword},
       {pm1a_cnt_blk, dword},
       {pm1b_cnt_blk, dword},
       {pm2_cnt_blk, dword},
       {pm_tmr_blk, dword},
       {gpe0_blk, dword},
       {gpe1_blk, dword},
       {pm1_evt_len, byte},
       {pm1_cnt_len, byte},
       {pm2_cnt_len, byte},
       {pm_tmr_len, byte},
       {gpe0_blk_len, byte},
       {gpe1_blk_len, byte},
       {gpe1_base, byte},
       {cst_cnt, byte},
       {p_lvl2_lat, word},
       {p_lvl3_lat, word},
       {flush_size, word},
       {flush_stride, word},
       {duty_offset, byte},
       {duty_width, byte},
       {day_alrm, byte},
       {mon_alrm, byte},
       {century, byte},
       {iapc_boot_arch, word},
       {unused, byte},
       {flags, dword},
       {reset_reg, {binary, 12}},
       {reset_value, byte},
       {arm_boot_arch, word},
       {fadt_minor_version, byte},
       {x_firmware_ctrl, qword},
       {x_dsdt, qword},
       {x_pm1a_evt_blk, {binary, 12}},
       {x_pm1b_evt_blk, {binary, 12}},
       {x_pm1a_cnt_blk, {binary, 12}},
       {x_pm1b_cnt_blk, {binary, 12}},
       {x_pm2_cnt_blk, {binary, 12}},
       {x_pm_tmr_blk, {binary, 12}},
       {x_gpe0_blk, {binary, 12}},
       {x_gpe1_blk, {binary, 12}},
       {sleep_control_reg, {binary, 12}},
       {sleep_status_reg, {binary, 12}},
       {hypervisor_vendor_identity, {binary, 8}}
      ],
     Data).
